Repository BinaryStudioAcademy/bsa-2018-watcher, pull requests merged in 2018-08, with the labels that each got.

#88 fixed hamburger icon
  frontend/src/app/landing/landing.component.header.sass
Labels: bug

#116 Feature/chat v0.4
  frontend/src/app/shell/shell.module.ts
Labels: fix

#145 Feature/custom confirm dialog
  frontend/src/app/notification/custom-confirm-dialog/custom-confirm-dialog.component.html
  frontend/src/app/notification/custom-confirm-dialog/custom-confirm-dialog.component.sass
  frontend/src/app/notification/custom-confirm-dialog/custom-confirm-dialog.component.ts
Labels: fix

#147 Feature/dashboard items
  DataAccumulator/DataAccumulator.DataAccessLayer/Entities/CollectedData.cs
  DataAccumulator/DataAccumulator.DataAccessLayer/Interfaces/IDataAccumulatorRepository.cs
  DataAccumulator/DataAccumulator.DataAccessLayer/Repositories/DataAccumulatorRepository.cs
  backend/Watcher.Core/Services/CollectedDataService.cs
Labels: enhancement

#178 Feature/chat notification
  backend/Watcher.Core/Hubs/NotificationsHub.cs
  backend/Watcher.Core/Interfaces/IChatsService.cs
  backend/Watcher.Core/Services/ChatsService.cs
  backend/Watcher.Core/Services/NotificationService.cs
  backend/Watcher.Core/Services/NotificationSettingsService.cs
  backend/Watcher/Hubs/ChatHub.cs
  frontend/src/app/admin/feedback-list/feedback-list.component.ts
  frontend/src/app/app.module.ts
  frontend/src/app/chat/chat-create-popup/chat-create-popup.component.html
  frontend/src/app/chat/chat-create-popup/chat-create-popup.component.ts
  frontend/src/app/chat/chat.component.sass
  frontend/src/app/chat/chat.component.ts
  frontend/src/app/chat/conversation-settings-popup/conversation-settings-popup.component.html
  frontend/src/app/chat/conversation-settings-popup/conversation-settings-popup.component.ts
  frontend/src/app/core/hubs/notifications.hub.ts
  frontend/src/app/notification/notification-block/notification-block.component.ts
  frontend/src/app/notifications/notification/notification.component.html
  frontend/src/app/notifications/notification/notification.component.sass
  frontend/src/app/notifications/notification/notification.component.ts
  frontend/src/app/notifications/notifications-routing.module.ts
  frontend/src/app/notifications/notifications.module.ts
  frontend/src/app/shared/models/notification.model.ts
Labels: feature

#179 Fix/userchat backend
  backend/Watcher.Common/Dtos/MessageDto.cs
  backend/Watcher.Common/MoveToFrontend/message.model.ts
  backend/Watcher.Core/Hubs/ChatsHub.cs
  backend/Watcher.Core/Services/ChatsService.cs
  backend/Watcher.DataAccess/Interfaces/IUnitOfWork.cs
  backend/Watcher.DataAccess/Interfaces/Repositories/IChatsRepository.cs
  backend/Watcher.DataAccess/Interfaces/Repositories/IUserChatRepository.cs
  backend/Watcher.DataAccess/Repositories/ChatsRepository.cs
  backend/Watcher.DataAccess/Repositories/UserChatRepository.cs
  backend/Watcher.DataAccess/Repositories/UserOrganizationRepository.cs
  backend/Watcher.DataAccess/UnitOfWork.cs
  backend/Watcher/Controllers/ResponsesController.cs
  backend/Watcher/Controllers/RolesController.cs
  backend/Watcher/Controllers/SamplesController.cs
  backend/Watcher/Startup.cs
Labels: fix
